using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ManagementHub.Storage.Migrations
{
    /// <inheritdoc />
    public partial class FixNgbTransferControlBoolTypes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Fix columns that were incorrectly created on PostgreSQL when the migration
            // was originally generated targeting SQLite:
            // 1. Boolean columns declared as INTEGER — Npgsql refuses to read them as bool.
            // 2. The id PK missing IDENTITY — causing null-id NOT NULL violations on insert.
            // This is a no-op on SQLite (which handles booleans as INTEGER natively and does
            // not support ALTER COLUMN TYPE or ADD GENERATED AS IDENTITY).
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                // Fix boolean column types.
                migrationBuilder.Sql(
                    "ALTER TABLE team_invitations ALTER COLUMN is_internal_transfer TYPE boolean USING (is_internal_transfer::boolean);");
                migrationBuilder.Sql(
                    "ALTER TABLE national_governing_bodies ALTER COLUMN auto_approve_internal_transfers TYPE boolean USING (auto_approve_internal_transfers::boolean);");
                migrationBuilder.Sql(
                    "ALTER TABLE ngb_transfer_approvals ALTER COLUMN is_origin_ngb TYPE boolean USING (is_origin_ngb::boolean);");

                // Add IDENTITY to the id PK which was created without a sequence.
                // Guard against fresh databases where the fixed original migration already
                // created the column with IDENTITY (adding it twice raises error 55000).
                migrationBuilder.Sql(@"
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    WHERE c.relname = 'ngb_transfer_approvals' AND a.attname = 'id' AND a.attidentity <> ''
  ) THEN
    ALTER TABLE ngb_transfer_approvals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    "ALTER TABLE team_invitations ALTER COLUMN is_internal_transfer TYPE integer USING (is_internal_transfer::integer);");
                migrationBuilder.Sql(
                    "ALTER TABLE national_governing_bodies ALTER COLUMN auto_approve_internal_transfers TYPE integer USING (auto_approve_internal_transfers::integer);");
                migrationBuilder.Sql(
                    "ALTER TABLE ngb_transfer_approvals ALTER COLUMN is_origin_ngb TYPE integer USING (is_origin_ngb::integer);");
            }
        }
    }
}
